---
abstract: 'Perl client to the Datamuse (https://www.datamuse.com/api/) API'
author:
  - 'James Wright <jwright@cpan.org>'
build_requires: {}
configure_requires:
  Module::Build::Tiny: '0.034'
dynamic_config: 0
generated_by: 'App::ModuleBuildTiny version 0.025, CPAN::Meta::Converter version 2.150010'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: Datamuse-API
provides:
  Datamuse::API:
    file: lib/Datamuse/API.pm
    version: '0.01'
requires:
  Data::Perl: '0'
  Future::HTTP: '0'
  HTTP::Tiny: '0'
  IO::Socket::SSL: '1.56'
  JSON: '0'
  Moo: '0'
  MooX::HandlesVia: '0'
  MooX::TypeTiny: '0'
  Net::SSLeay: '1.49'
  Sub::Quote: '0'
  Type::Tiny: '1.004000'
version: '0.01'
x_serialization_backend: 'CPAN::Meta::YAML version 0.018'
x_spdx_expression: 'Artistic-1.0-Perl OR GPL-1.0-or-later'
